### ISSUE TITLE
Not working on MacOS 12.3 anymore

### ISSUE THREAD

**Issue by pfederi** [skleinei/alfred-confluence#12]
The Workflow is not working on MacOS 12.3 anymore due to deprecation of Python 2.

**Comment by Knapsack44** [comment]
Thanks for your @gaborszakacs.
Alfred also provides instructions for installing Python 2 under Monterey on its [website](https://www.alfredapp.com/help/kb/python-2-monterey/)
```shell 
export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
eval "$(brew shellenv)"
brew install pyenv
pyenv install 2.7.18
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "${HOMEBREW_PREFIX}/bin/python"
```
For further clarification of your last step, which is essential
> I had some issues with auto-update, I put an early return [in that function](https://github.com/skleinei/alfred-confluence/blob/f992894d21525150e54ee1da90a01931b0364e09/src/lib/workflow/workflow.py#L2468)

Go to `<workflowdir>/lib/workflow/workflow.py` and add a new line with content `return`as line 2482 as shown [here](https://v.usetapes.com/YGO76TVN4d).

**Comment by pfederi** [comment]
I'm having the following Problem. Any ideas?
workflow.py:2243 ERROR    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

**Comment by jovobe** [comment]
I just rewrote the workflow in rust. You can find the project right [here](https://github.com/jovobe/alfred-confluence-workflow). It should offer the same functionality as the Python based workflow extended by the possibility to use an access token for authentication.

**Comment by GabLeRoux** [comment]
For those who would like to contribute, this upstream pr seems promising:  
https://github.com/deanishe/alfred-workflow/pull/184 👍

**Comment by skleinei** [comment]
Hi all, thanks for your efforts to fix this. I've just rewritten Confluence Quicksearch for Alfred to work with Python 3 (and hence macOS 12.3). The new version also requires Alfred 5, because the new version uses Alfreds' new workflow configuration.

Read more: https://github.com/skleinei/alfred-confluence/discussions/16
